import torch
import yaml
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from src.model import AnomalyAutoencoder

# 1. Initialize FastAPI application
app = FastAPI(
    title="Financial Fraud Detection API",
    description="Real-time transaction anomaly detection server using a PyTorch Autoencoder.",
    version="1.0.0"
)

# 2. Define the expected JSON data structure for incoming transactions
class TransactionInput(BaseModel):
    transaction_amount: float
    available_money: float
    current_balance: float
    credit_limit: float
    card_present: int  # 1 for True, 0 for False
    cvv_match: int     # 1 for True, 0 for False

# 3. Global variables to hold model and configuration limits
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = None
config = None

@app.on_event("startup")
def load_resources():
    """Executes automatically when the server starts up."""
    global model, config
    
    # Load settings from config.yaml
    with open("config.yaml", "r") as f:
        config = yaml.safe_load(f)
        
    # Initialize the Autoencoder network with the fixed 6 features
    model = AnomalyAutoencoder(input_dim=6).to(device)
    
    # Load weights generated by main.py
    try:
        model.load_state_dict(torch.load('models/autoencoder_fraud.pth', map_location=device))
        model.eval()
        print("API successfully loaded the trained PyTorch model weights.")
    except FileNotFoundError:
        print("WARNING: 'models/autoencoder_fraud.pth' not found. Please run main.py first to train the model!")

@app.get("/")
def root():
    """Simple health check endpoint."""
    return {"status": "online", "message": "Fraud Detection API is running smoothly."}

@app.post("/predict")
def predict_transaction(tx: TransactionInput):
    """
    Receives a single financial transaction, processes it, 
    and checks if it deviates enough from regular patterns to be flagged as fraud.
    """
    if model is None:
        raise HTTPException(status_code=500, detail="Model weights are not loaded on the server.")
        
    # Convert input features into a structured NumPy array
    features = np.array([[
        tx.transaction_amount,
        tx.available_money,
        tx.current_balance,
        tx.credit_limit,
        tx.card_present,
        tx.cvv_match
    ]], dtype=np.float32)
    
    # Convert to PyTorch Tensor
    tensor_input = torch.FloatTensor(features).to(device)
    
    # Run forward pass to reconstruct features
    with torch.no_grad():
        reconstructed = model(tensor_input)
        
    # Calculate Mean Squared Error (MSE) for this specific record
    mse = torch.mean((tensor_input - reconstructed) ** 2).item()
    
    # Fetch the optimal threshold from config.yaml
    threshold = config['evaluation']['optimal_threshold']
    
    # Classify transaction: If error is strictly greater than threshold -> Anomaly!
    is_fraud = int(mse > threshold)
    
    return {
        "reconstruction_error": float(f"{mse:.6f}"),
        "threshold": float(threshold),
        "is_fraud": is_fraud,
        "verdict": "FRAUD ALERT" if is_fraud == 1 else "APPROVED"
    }
