# -*- coding: utf-8 -*-
"""data_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hx-nrYPtUN-mTAyt0FpUTO1z4-jI5Ee1
"""

import pandas as pd
import torch
import zipfile
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader

def prepare_data(zip_path='data/creditcard.zip', batch_size=256):

    with zipfile.ZipFile(zip_path, 'r') as z:
        csv_name = z.namelist()[0]
        with z.open(csv_name) as f:
            df = pd.read_csv(f)

    features_to_use = [
        'transactionAmount', 'availableMoney', 'currentBalance', 'creditLimit',
        'cardPresent', 'cvv_Match', 'isFraud'
    ]

    df = df[features_to_use].dropna()

    df['cardPresent'] = df['cardPresent'].astype(int)
    df['cvv_Match'] = df['cvv_Match'].astype(int)

    scaler = StandardScaler()
    num_cols = ['transactionAmount', 'availableMoney', 'currentBalance', 'creditLimit']
    df[num_cols] = scaler.fit_transform(df[num_cols])

    normal_tx = df[df['isFraud'] == 0]
    fraud_tx = df[df['isFraud'] == 1]

    train_normal, temp_normal = train_test_split(normal_tx, test_size=0.2, random_state=42)
    val_normal, test_normal = train_test_split(temp_normal, test_size=0.5, random_state=42)

    X_train = train_normal.drop(['isFraud'], axis=1).values
    X_val = val_normal.drop(['isFraud'], axis=1).values

    test_set = pd.concat([test_normal, fraud_tx])
    X_test = test_set.drop(['isFraud'], axis=1).values
    y_test = test_set['isFraud'].values

    train_dataset = TensorDataset(torch.FloatTensor(X_train))
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    val_dataset = TensorDataset(torch.FloatTensor(X_val))
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    input_dim = X_train.shape[1]

    return train_loader, val_loader, X_test, y_test, input_dim