# -*- coding: utf-8 -*-
"""data_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hx-nrYPtUN-mTAyt0FpUTO1z4-jI5Ee1
"""

import pandas as pd
import torch
import zipfile
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader

def prepare_data(zip_path='data/creditcard.zip', batch_size=256):
    """
    Opens the zip archive, extracts the CSV dataset, handles data preprocessing,
    and splits the dataset into Train/Val/Test subsets for unsupervised learning.
    """
    # 1. Open the zip file and read the first CSV inside directly into Pandas
    with zipfile.ZipFile(zip_path, 'r') as z:
        csv_name = z.namelist()[0] 
        with z.open(csv_name) as f:
            df = pd.read_csv(f)
            
    # 2. Feature Selection based on Exploratory Data Analysis (EDA)
    # Keeping highly correlated features and scaling numeric limits
    features_to_use = [
        'transactionAmount', 'availableMoney', 'currentBalance', 'creditLimit',
        'cardPresent', 'cvv_Match', 'isFraud'
    ]
    df = df[features_to_use].dropna()
    
    # Convert boolean indicators (True/False) to numeric binary flags (1/0)
    df['cardPresent'] = df['cardPresent'].astype(int)
    df['cvv_Match'] = df['cvv_Match'].astype(int)
    
    # 3. Standardize continuous numerical values (Zero mean and unit variance)
    scaler = StandardScaler()
    num_cols = ['transactionAmount', 'availableMoney', 'currentBalance', 'creditLimit']
    df[num_cols] = scaler.fit_transform(df[num_cols])
    
    # 4. Separate normal transactions from fraudulent ones
    normal_tx = df[df['isFraud'] == 0]
    fraud_tx = df[df['isFraud'] == 1]
    
    # 5. Split normal transactions: 80% Train, 10% Validation, 10% Test
    train_normal, temp_normal = train_test_split(normal_tx, test_size=0.2, random_state=42)
    val_normal, test_normal = train_test_split(temp_normal, test_size=0.5, random_state=42)
    
    # Drop labels for unsupervised training (Autoencoder learns normal patterns only)
    X_train = train_normal.drop(['isFraud'], axis=1).values
    X_val = val_normal.drop(['isFraud'], axis=1).values
    
    # 6. Create the final evaluation test set containing both normal data and fraud samples
    test_set = pd.concat([test_normal, fraud_tx])
    X_test = test_set.drop(['isFraud'], axis=1).values
    y_test = test_set['isFraud'].values
    
    # 7. Convert NumPy arrays into PyTorch Tensors and wrap them in DataLoaders
    train_dataset = TensorDataset(torch.FloatTensor(X_train))
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    
    val_dataset = TensorDataset(torch.FloatTensor(X_val))
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    
    input_dim = X_train.shape[1]
    
    return train_loader, val_loader, X_test, y_test, input_dim
